"""добааление поля папрля

Revision ID: 007ab1a399af
Revises: 5a1c94e2222a
Create Date: 2026-05-28 09:06:01.687434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007ab1a399af'
down_revision: Union[str, Sequence[str], None] = '5a1c94e2222a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем  новое поле hashed_password в таблицу users с пустыми значениями, так как в существующих записях нет данных для этого поля
    op.add_column('users', sa.Column('hashed_password', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET hashed_password = '$2b$12$PM9FDwsEkoa/nZHfS41GBuKUj5nznq9vwxEoTUE6zXzw/etp3kFeS' WHERE" \
    " hashed_password IS NULL ")  # Заполняем новое поле дефолтным значением
    op.alter_column('users', 'hashed_password', nullable=False)  # Делаем поле обязательным

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
