"""Переименование колонки с типом должника

Revision ID: 1fb956fe07cb
Revises: 7afad159c7a9
Create Date: 2026-08-29 11:17:58.516102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fb956fe07cb'
down_revision: Union[str, Sequence[str], None] = '7afad159c7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debtors', 'type', new_column_name='debtor_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
