"""В case добавлен столбец с датой дела, так как он необходим для заполнения запровос в госорганы

Revision ID: 2a359bf62ca7
Revises: d31b646904dc
Create Date: 2026-10-01 09:54:59.396354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a359bf62ca7'
down_revision: Union[str, Sequence[str], None] = 'd31b646904dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('date_case', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'date_case')
    # ### end Alembic commands ###
