"""Добавление таблицы courts с наименованием судов и связи с датами судов

Revision ID: 75e6473a08c7
Revises: 9d7814664173
Create Date: 2026-09-03 11:46:25.871409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e6473a08c7'
down_revision: Union[str, Sequence[str], None] = '9d7814664173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('court_sessions', sa.Column('court_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'court_sessions', 'courts', ['court_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'court_sessions', type_='foreignkey')
    op.drop_column('court_sessions', 'court_id')
    op.drop_table('courts')
    # ### end Alembic commands ###
