"""Добавление Debtor, DebtorType. Переименование debtor в таблице Case в debtor_name. Связь Debtor и Case

Revision ID: 78cfb7777299
Revises: 007ab1a399af
Create Date: 2026-08-27 11:29:05.572299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cfb7777299'
down_revision: Union[str, Sequence[str], None] = '007ab1a399af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debtors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LEGAL', 'PHYSICAL', name='debtortype'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('inn', sa.Integer(), nullable=True),
    sa.Column('snils', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # 1. Переименовываем столбец (данные сохраняются!)
    op.alter_column('cases', 'debtor', new_column_name='debtor_name')
    op.add_column('cases', sa.Column('debtor_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_cases_debtor_id', 'cases', 'debtors', ['debtor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
        # 1. Удаляем внешний ключ (по имени, которое задали в upgrade)
    op.drop_constraint('fk_cases_debtor_id', 'cases', type_='foreignkey')

    # 2. Удаляем столбец debtor_id
    op.drop_column('cases', 'debtor_id')

    # 3. Переименовываем debtor_name обратно в debtor
    op.alter_column('cases', 'debtor_name', new_column_name='debtor')

    # 4. Удаляем таблицу debtors
    op.drop_table('debtors')
    # ### end Alembic commands ###
