"""миграция для переноса наименования должника в иаблицу debtors

Revision ID: 7afad159c7a9
Revises: 78cfb7777299
Create Date: 2026-08-27 22:21:09.875443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afad159c7a9'
down_revision: Union[str, Sequence[str], None] = '78cfb7777299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind() # Получаем соединение
    result = connection.execute(
        sa.text("SELECT id, debtor_name FROM cases WHERE debtor_id is NULL AND debtor_name IS NOT NULL")
    ).fetchall()

    # Вставляем построчно данные из таблицы cases в debtors
    for case_id, name in result:
        row = connection.execute(
            sa.text(
                "INSERT INTO debtors (type, name) VALUES (:type, :name) RETURNING id"
            ), {"type" : "PHYSICAL", "name": name}
        )
        debtor_id = row.scalar()
        connection.execute(
            sa.text(
                "UPDATE cases SET debtor_id = :debtor_id WHERE id = :case_id"
            ), {"debtor_id": debtor_id, "case_id": case_id}
        )

    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
