"""Переименование колонки с типом должника

Revision ID: 8a39d2949297
Revises: 1fb956fe07cb
Create Date: 2026-08-29 11:22:54.719825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a39d2949297'
down_revision: Union[str, Sequence[str], None] = '1fb956fe07cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debtors', 'debtor_name', new_column_name='debtor_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
