"""Изменение типа колонки date в ParsDocument на iso формат

Revision ID: 9d7814664173
Revises: 8a39d2949297
Create Date: 2026-09-02 12:02:33.035424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7814664173'
down_revision: Union[str, Sequence[str], None] = '8a39d2949297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(table_name='pars_documents', column=sa.Column('date_iso', sa.Date(), nullable=True))
    connection = op.get_bind()
    connection.execute(
        sa.text("""
            UPDATE pars_documents
            SET date_iso = TO_DATE(date, 'DD.MM.YYYY')
            WHERE date IS NOT NULL AND date != ''
        """),
    )
    # Удаление старой колонки
    op.drop_column("pars_documents", "date")
    # Переименование 
    op.alter_column("pars_documents", "date_iso", new_column_name="date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
