"""в таблицу User добавлено поле email, добавлено nullable=True для telephone, telegram_id, добавление таблицы SupportTicket

Revision ID: c67e4221ca76
Revises: 9cb7226c24c5
Create Date: 2026-05-18 15:45:46.452719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67e4221ca76'
down_revision: Union[str, Sequence[str], None] = '9cb7226c24c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.Text(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
