"""добавление колонки link в таблице cases

Revision ID: d31b646904dc
Revises: 9a2345ddd196
Create Date: 2026-09-24 16:16:58.798362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31b646904dc'
down_revision: Union[str, Sequence[str], None] = '9a2345ddd196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'link')
    # ### end Alembic commands ###
