"""Добавление таблиц адресов(почтовый и проживания), банка, счетов

Revision ID: e6ba1699312b
Revises: 75e6473a08c7
Create Date: 2026-09-11 11:49:44.991757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ba1699312b'
down_revision: Union[str, Sequence[str], None] = '75e6473a08c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.Text(), nullable=False),
    sa.Column('house', sa.Text(), nullable=False),
    sa.Column('building', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_index', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residential_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('flat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mail_address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mail_address_id'], ['mail_address.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('debtors', sa.Column('birth_region_id', sa.Integer(), nullable=True))
    op.add_column('debtors', sa.Column('residential_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_debtors_birth_region', 'debtors', 'region', ['birth_region_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_debtors_residential_address', 'debtors', 'residential_address', ['residential_address_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
     # 1. Удалить FK-ограничения на колонки, которые сейчас удалим
    op.drop_constraint('fk_debtors_residential_address', 'debtors', type_='foreignkey')
    op.drop_constraint('fk_debtors_birth_region', 'debtors', type_='foreignkey')
    # 2. Теперь можно удалить сами колонки (FK их больше не держит) 
    op.drop_column('debtors', 'residential_address_id')
    op.drop_column('debtors', 'birth_region_id')
    # 3. Удалить таблицы, которые добавили в upgrade
    op.drop_table('account')
    op.drop_table('bank')
    op.drop_table('residential_address')
    op.drop_table('mail_address')
    op.drop_table('region')
    op.drop_table('address')
    # ### end Alembic commands ###
